### ISSUE TITLE
Commands should have no dash or two dashes, not one?

### ISSUE THREAD

**Issue by pianocomposer321** [aloussase/viper#2]
The convention with linux cli tools is to have subcommands with no dashes, single-character flags with a single dash, or long-name flags with double dashes. This breaks that convention. It's not a huge deal, but it is expected and it would be easier to change this now then down the road, assuming this gets a bunch of users.

**Comment by aloussase** [comment]
Yes, I think you are right. The commands currently begin with a dash because of the library I use to parse them, but I can switch to a new library so they have a more standard form. I will start working on that soon. Thanks for the feedback!

**Comment by aloussase** [comment]
Reopened, will close when I have the fix update done.

**Comment by aloussase** [comment]
I pushed a new tag with release 1.0.0 since this change broke compatibility with the first version. Hopefully this is the only change like this. Command names are now more unix-like. Feel free to provide any more feedback and close the issue yourself when you are done, thanks again!

**Comment by pianocomposer321** [comment]
I haven't tried it yet (I will when I get a chance), but it looks much better from the README 👍. As far as I'm concerned, this is fixed.
